### ISSUE TITLE
Muted colors

### ISSUE THREAD

**Issue by tillkruss** [andrewmcodes/warp-one-dark-darker#2]
My colors seem really muted, how can I have them as vibrant as in the screenshots?

<img width="758" alt="Screen Shot 2022-09-27 at 2 37 01 PM" src="https://user-images.githubusercontent.com/665029/192640347-6d74ae97-dda7-49c5-9c68-92a580a41eb9.png">

**Comment by andrewmcodes** [comment]
@tillkruss I updated the theme and screenshot based on the original theme. 

If you're still not happy, this [VS Code extension](https://marketplace.visualstudio.com/items?itemName=haack.warp-companion) can automatically create a warp theme based on the VS Code theme so I'd check that out.
